name: e2e test

on: [push, pull_request]

# playwright testを走らせるe2eテストのジョブを定義
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: build
        run: npm run build
      - name: Run e2e test
        run: npm run test:e2e
