name: e2e test

on: 
  deployment_status:

# playwright testを走らせるe2eテストのジョブを定義
jobs:
  e2e-test:
    if: |
      github.event.deployment_status.state == 'success' &&
      github.event.deployment_status.environment == 'Preview'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
      - name: Install dependencies
        run: npm ci
      - name: Install playwright
        run: npm run install:playwright
      - name: Run e2e test
        run: npm run test:e2e
        env:
          BASE_URL: ${{ github.event.deployment_status.environment_url }}
