name: Unit Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install and cache dependencies
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Run test
        run: npm run test